[startup.cgroup]
name = "bash"
#must_exit =true to force services running after
#this one to only run after this one exits
must_exit = true
after = ["init"]
data = """
mount -t tmpfs cgroup_root /sys/fs/cgroup

subsys="cpuset cpu cpuacct blkio memory devices freezer net_cls perf_event net_prio hugetlb"

for sys in $subsys; do
    mkdir -p /sys/fs/cgroup/$sys
    mount -t cgroup $sys -o $sys /sys/fs/cgroup/$sys/
done
"""