[startup."ssh.init"]
name = "core.system"
running_delay = -1

[startup."ssh.init".args]
name = "mkdir"
args = ["-p", "/var/run/sshd"]

[startup.sshd]
after = ["ssh.init"]
name = "core.system"

[startup.sshd.args]
name = "/usr/sbin/sshd"
args = ["-D"]
