#leave /tmp and /opt/jumpscale8 in this file, gets replaced during installation

[main]
max_jobs = 200
message_ID_file = "/var/run/core.mid"
include = "/etc/g8os/g8os.d"
network = "/etc/g8os/network.toml"

[controllers]
#[controllers.main]
#url = "http://localhost:8966"
#[controllers.main.security]
#UNCOMMENT THE FOLLOWING LINES TO USE SSL
#client_certificate = "/path/to/client-test.crt"
#client_certificate_key = "/path/to/client-test.key"

# defines an extra CA to trust (used in case of server self-signed certs)
# should be empty string otherwise.

#certificate_authority = "/path/to/server.crt"

[channel]
cmds = [] # empty for long polling from all defined controllers, or specif controllers keys


#the very basic agent extensions. Also please check the toml files under
#the Main.Include folder for more extensions
[extension.syncthing]
binary = "/usr/local/bin/syncthing"
cwd = "/usr/lib/g8os/extensions/"
args = ["-home", "./syncthing", "-gui-address", "127.0.0.1:28384"]

[extension.syncthing.env]
HOME="/usr/lib/g8os/extensions/syncthing"

[extension.sync]
#syncthing extension
binary = "python"
cwd = "/usr/lib/g8os/extensions/sync"
args = ["{name}.py"]
    [extension.sync.env]
    PYTHONPATH = "../:/opt/jumpscale8/lib"
    SYNCTHING_URL = "http://localhost:28384"

[extension.jumpscript]
binary = "python"
cwd = "/usr/lib/g8os/extensions/jumpscript"
args = ["wrapper.py", "{domain}", "{name}"]
    [extension.jumpscript.env]
    SOCKET = "/tmp/jumpscript.sock"
    PYTHONPATH = "../"

[extension.jumpscript_content]
binary = "python"
cwd = "/usr/lib/g8os/extensions/jumpscript"
args = ["wrapper_content.py"]
    [extension.jumpscript_content.env]
    SOCKET = "/tmp/jumpscript.sock"
    PYTHONPATH = "../"

[extension.js_daemon]
binary = "python"
cwd = "/usr/lib/g8os/extensions/jumpscript"
args = ["executor.py"]
    [extension.js_daemon.env]
    SOCKET = "/tmp/jumpscript.sock"
    PYTHONPATH = "../:/opt/jumpscale8/lib"
    JUMPSCRIPTS_HOME = "/opt/jumpscale8/apps/agent8/jumpscripts/"

[extension.bash]
binary = "bash"
args = ['-c', 'T=`mktemp` && cat > $T && bash $T; EXIT=$?; rm -rf $T; exit $EXIT']

[logging]
    [logging.db]
    type = "DB"
    address = "/var/log/g8os"
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    #[logging.ac]
    #type = "AC"
    #flush_int = 300 # seconds (5min)
    #batch_size = 1000 # max batch size, force flush if reached this count.
    #controllers = [] # empty for all controllers, or controllers keys
    #levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60000 # milliseconds (1 min)

[stats.ac]
enabled = false
controllers = [] # empty for all controllers, or controllers keys

[stats.redis]
enabled = false
flush_interval = 100 # millisecond
address = "localhost:6379"

[hubble]
controllers = [] # accept forwarding commands and connections from all controllers. Or specific controllers by name
