matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      if: type IN (api, cron)

      install:
        - pip3 install python-dateutil requests
        - curl -s https://install.zerotier.com/ | sudo bash
        - pip3 install git+https://github.com/gigforks/packet-python.git
        - pip3 install zerotier

      script:
        - ls