language: python
sudo: true
dist: trusty

jobs:
  include:
  - stage: Prepare
      install: pip3 install packet
      script: echo prepare

    - stage: Test
      script: echo test 1
      script: echo test 2
