doc:
  property:
  - password: ''
  - groups: ''
  - g8client: ''
  - email: ''
  - provider: ''
links:
  consume:
  - argname: g8client
    auto: true
    max: 100
    min: 0
    role: g8client
    argname: 'g8client'
recurring: []
